// Album and radio station data sourced from https://github.com/Omoluabi1003/Ariyo-AI

const albums = [
  {
    name: 'Kindness',
    cover: 'https://raw.githubusercontent.com/Omoluabi1003/Ariyo-AI/main/Kindness%20Cover%20Art.jpg',
    tracks: [
      { src: 'https://raw.githubusercontent.com/Omoluabi1003/Ariyo-AI/main/A%20Very%20Good%20Bad%20Guy%20v3.mp3', title: 'A Very Good Bad Guy v3' },
      { src: 'https://raw.githubusercontent.com/Omoluabi1003/Ariyo-AI/main/Dem%20Wan%20Shut%20Me%20Up.mp3', title: 'Dem Wan Shut Me Up' },
      { src: 'https://raw.githubusercontent.com/Omoluabi1003/Ariyo-AI/main/EFCC.mp3', title: 'EFCC' },
      { src: 'https://raw.githubusercontent.com/Omoluabi1003/Ariyo-AI/main/Emergency.mp3', title: 'Emergency' },
      { src: 'https://raw.githubusercontent.com/Omoluabi1003/Ariyo-AI/main/Film%20Trick%20Election.mp3', title: 'Film Trick Election' },
      { src: 'https://raw.githubusercontent.com/Omoluabi1003/Ariyo-AI/main/Gbas%20Gbos.mp3', title: 'Gbas Gbos' },
      { src: 'https://raw.githubusercontent.com/Omoluabi1003/Ariyo-AI/main/Kindness%20(Remastered).mp3', title: 'Kindness (Remastered)' },
      { src: 'https://raw.githubusercontent.com/Omoluabi1003/Ariyo-AI/main/Locked%20Away.mp3', title: 'Locked Away' },
      { src: 'https://raw.githubusercontent.com/Omoluabi1003/Ariyo-AI/main/Multi%20choice%20palava.mp3', title: 'Multi choice palava' },
      { src: 'https://raw.githubusercontent.com/Omoluabi1003/Ariyo-AI/main/Na%20My%20Turn.mp3', title: 'Na My Turn' },
      { src: 'https://raw.githubusercontent.com/Omoluabi1003/Ariyo-AI/main/Ogoni%20Anthem%20(Remastered).mp3', title: 'Ogoni Anthem (Remastered)' },
      { src: 'https://raw.githubusercontent.com/Omoluabi1003/Ariyo-AI/main/Ogoni%20Anthem.mp3', title: 'Ogoni Anthem' },
      { src: 'https://raw.githubusercontent.com/Omoluabi1003/Ariyo-AI/main/Rich%20Pauper.mp3', title: 'Rich Pauper' },
      { src: 'https://raw.githubusercontent.com/Omoluabi1003/Ariyo-AI/main/Senator%20Natasha’s%20Whisper.mp3', title: 'Senator Natasha’s Whisper' },
      { src: 'https://raw.githubusercontent.com/Omoluabi1003/Ariyo-AI/main/Sharing%20Formula.mp3', title: 'Sharing Formula' },
      { src: 'https://raw.githubusercontent.com/Omoluabi1003/Ariyo-AI/main/Show%20Of%20Shame%20v3%20(Remastered).mp3', title: 'Show Of Shame v3 (Remastered)' },
      { src: 'https://raw.githubusercontent.com/Omoluabi1003/Ariyo-AI/main/Subsidy.mp3', title: 'Subsidy' },
      { src: 'https://raw.githubusercontent.com/Omoluabi1003/Ariyo-AI/main/Vex%20Money.mp3', title: 'Vex Money' },
      { src: 'https://raw.githubusercontent.com/Omoluabi1003/Ariyo-AI/main/Working%20on%20myself.mp3', title: 'Working on myself' }
    ]
  },
  {
    name: 'Street Sense',
    cover: 'https://raw.githubusercontent.com/Omoluabi1003/Ariyo-AI/main/Street_Sense_Album_Cover.jpg',
    tracks: [
      { src: 'https://raw.githubusercontent.com/Omoluabi1003/Ariyo-AI/main/Na%20We%20Dey.mp3', title: 'Na We Dey' },
      { src: 'https://raw.githubusercontent.com/Omoluabi1003/Ariyo-AI/main/No%20Be%20My%20Story.mp3', title: 'No Be My Story' },
      { src: 'https://raw.githubusercontent.com/Omoluabi1003/Ariyo-AI/main/Algorithm%20Of%20Life.mp3', title: 'Algorithm of life' },
      { src: 'https://raw.githubusercontent.com/Omoluabi1003/Ariyo-AI/main/Babygirl.mp3', title: 'Babygirl' },
      { src: 'https://raw.githubusercontent.com/Omoluabi1003/Ariyo-AI/main/Ubuntu.mp3', title: 'Ubuntu' },
      { src: 'https://raw.githubusercontent.com/Omoluabi1003/Ariyo-AI/main/Blood%20On%20The%20Lithium.mp3', title: 'Blood On The Lithium' },
      { src: 'https://raw.githubusercontent.com/Omoluabi1003/Ariyo-AI/main/Oluwa%20You%20Too%20Good.mp3', title: 'Oluwa You Too Good' },
      { src: 'https://raw.githubusercontent.com/Omoluabi1003/Ariyo-AI/main/Freedom%20of%20Speech.mp3', title: 'Freedom of Speech' },
      { src: 'https://raw.githubusercontent.com/Omoluabi1003/Ariyo-AI/main/E%20Get%20Why.mp3', title: 'E Get Why' },
      { src: 'https://raw.githubusercontent.com/Omoluabi1003/Ariyo-AI/main/Am%20grateful%20Lord.mp3', title: 'Am grateful Lord' },
      { src: 'https://raw.githubusercontent.com/Omoluabi1003/Ariyo-AI/main/Game%20Of%20Thrones.mp3', title: 'Game of Thrones' },
      { src: 'https://raw.githubusercontent.com/Omoluabi1003/Ariyo-AI/main/Give%20and%20Take%20(Reciprocity%20in%20love).mp3', title: 'Give and Take (Reciprocity in love)' },
      { src: 'https://raw.githubusercontent.com/Omoluabi1003/Ariyo-AI/main/Midas%20Touch.mp3', title: 'Midas Touch' },
      { src: 'https://raw.githubusercontent.com/Omoluabi1003/Ariyo-AI/main/Naija%20Youth;%20Rise.mp3', title: 'Naija Youth, Rise' },
      { src: 'https://raw.githubusercontent.com/Omoluabi1003/Ariyo-AI/main/Party%20No%20Go%20Stop.mp3', title: 'Party No Go Stop' },
      { src: 'https://raw.githubusercontent.com/Omoluabi1003/Ariyo-AI/main/Pigeonhole%20Gbedu.mp3', title: 'Pigeonhole Gbedu' },
      { src: 'https://raw.githubusercontent.com/Omoluabi1003/Ariyo-AI/main/Queen%20Warrior.mp3', title: 'Queen Warrior' },
      { src: 'https://raw.githubusercontent.com/Omoluabi1003/Ariyo-AI/main/Holy%20Vibes%20Only.mp3', title: 'Holy Vibes Only' },
      { src: 'https://raw.githubusercontent.com/Omoluabi1003/Ariyo-AI/main/Sengemenge.mp3', title: 'Sengemenge' },
      { src: 'https://raw.githubusercontent.com/Omoluabi1003/Ariyo-AI/main/Sowore.mp3', title: 'Sowore' },
      { src: 'https://raw.githubusercontent.com/Omoluabi1003/Ariyo-AI/main/Street%20Sense.mp3', title: 'Street Sense' },
      { src: 'https://raw.githubusercontent.com/Omoluabi1003/Ariyo-AI/main/VDM.mp3', title: 'VDM' },
      { src: 'https://raw.githubusercontent.com/Omoluabi1003/Ariyo-AI/main/We%20Are%20Not%20Doing%20That.mp3', title: 'We Are Not Doing That' },
      { src: 'https://raw.githubusercontent.com/Omoluabi1003/Ariyo-AI/main/Oil%20Money.mp3', title: 'Oil Money' },
      { src: 'https://raw.githubusercontent.com/Omoluabi1003/Ariyo-AI/main/Gbamsolutely.mp3', title: 'Gbamsolutely' },
      { src: 'https://raw.githubusercontent.com/Omoluabi1003/Ariyo-AI/main/Mic%20No%20Be%20For%20Waist.mp3', title: 'Mic No Be For Waist' }
    ]
  }
];

const radioStations = [
  { name: "Agidigbo 88.7 FM", location: "Ibadan", url: "https://agidigbostream.com.ng/radio/8000/radio.mp3", logo: "https://raw.githubusercontent.com/Omoluabi1003/Ariyo-AI/main/logo.jpg" },
  { name: "Nigeria Info FM", location: "Lagos", url: "https://nigeriainfofmlagos993-atunwadigital.streamguys1.com/nigeriainfofmlagos993", logo: "https://raw.githubusercontent.com/Omoluabi1003/Ariyo-AI/main/logo.jpg" },
  { name: "Radio Lagos FM", location: "Lagos", url: "https://servoserver.com.ng/ekofmradiolagos/stream/2/live.mp3", logo: "https://raw.githubusercontent.com/Omoluabi1003/Ariyo-AI/main/logo.jpg" },
  { name: "Brilla FM", location: "Lagos", url: "https://ice31.securenetsystems.net/BRILAMP3", logo: "https://raw.githubusercontent.com/Omoluabi1003/Ariyo-AI/main/logo.jpg" },
  { name: "Vision FM", location: "Kaduna", url: "https://stream-172.zeno.fm/92mxpb1akhruv?zt=eyJhbGciOiJIUzI1NiJ9.eyJzdHJlYW0iOiI5Mm14cGIxYWtocnV2IiwiaG9zdCI6InN0cmVhbS0xNzIuemVuby5fbSIsInJ0dGwiOjUsImp0aSI6ImV5OWlMMlhEU1JLMHNyYnd0b3F4ckEiLCJpYXQiOjE3NDM5MTU4MzgsImV4cCI6MTc0MzkxNTg5OH0.5sHfe_ukTnT2Fdiy83NdYdU0da51JkZXBgFoJVhg8_I", logo: "https://raw.githubusercontent.com/Omoluabi1003/Ariyo-AI/main/logo.jpg" },
  { name: "Fad FM", location: "Calabar", url: "https://radio.gotright.net/listen/fadfm/radio.mp3", logo: "https://raw.githubusercontent.com/Omoluabi1003/Ariyo-AI/main/logo.jpg" },
  { name: "JMPBliss Radio", location: "Ibadan", url: "https://stream-173.zeno.fm/ty5h0ecgka0uv?zt=eyJhbGciOiJIUzI1NiJ9.eyJzdHJlYW0iOiJ0eTVoMGVjZ2thMHV2IiwiaG9zdCI6InN0cmVhbS0xNzMuemVuby5mbSIsInJ0dGwiOjUsImp0aSI6InlRa2VIcE9aUV9TT2ZsZDJkWFhLZkEiLCJpYXQiOjE3NDQyMjQ1MjIsImV4cCI6MTc0NDIyNDU4Mn0.NE7xZDe19EjzpWN02xkt9XnorWH8FNdswwHdiih4dUI", logo: "https://raw.githubusercontent.com/Omoluabi1003/Ariyo-AI/main/logo.jpg" },
  { name: "Wazobia FM", location: "Lagos", url: "https://wazobiafmlagos951-atunwadigital.streamguys1.com/wazobiafmlagos951", logo: "https://raw.githubusercontent.com/Omoluabi1003/Ariyo-AI/main/logo.jpg" },
  { name: "Magic FM", location: "Aba", url: "https://radio.ifastekpanel.com:1565/stream", logo: "https://raw.githubusercontent.com/Omoluabi1003/Ariyo-AI/main/logo.jpg" },
  { name: "Inform Me Radio", location: "Nigeria", url: "https://stream-176.zeno.fm/ta1fke6sz1zuv?zt=eyJhbGciOiJIUzI1NiJ9.eyJzdHJlYW0iOiJ0YTFma2U2c3oxenV2IiwiaG9zdCI6InN0cmVhbS0xNzYuemVuby5mbSIsInJ0dGwiOjUsImp0aSI6ImlKY0pKbmZEVHlXOWNyZzJrSHV6X3ciLCJpYXQiOjE3NDQ3Njg5MzQsImV4cCI6MTc0NDc2ODk5NH0.80dAGY0KFczNyEb83ledkuxbeTscZSLM_H9XzWDkiX4", logo: "https://raw.githubusercontent.com/Omoluabi1003/Ariyo-AI/main/logo.jpg" },
  { name: "Inspiration 92.3 FM", location: "Lagos", url: "https://inspiration923fm-atunwadigital.streamguys1.com/inspiration923fm", logo: "https://raw.githubusercontent.com/Omoluabi1003/Ariyo-AI/main/logo.jpg" },
  { name: "Splash FM 105.5", location: "Ibadan", url: "http://edge.mixlr.com/channel/cfeki", logo: "https://raw.githubusercontent.com/Omoluabi1003/Ariyo-AI/main/logo.jpg" },
  { name: "The Beat 99.9 FM", location: "Lagos", url: "http://beatfmlagos.atunwadigital.streamguys1.com/beatfmlagos", logo: "https://raw.githubusercontent.com/Omoluabi1003/Ariyo-AI/main/logo.jpg" },
  { name: "Fresh 107.9 FM", location: "Abeokuta", url: "https://stream-144.zeno.fm/7gs2681gqeruv?zt=eyJhbGciOiJIUzI1NiJ9.eyJzdHJlYW0iOiI3Z3MyNjgxZ3FlcnV2IiwiaG9zdCI6InN0cmVhbS0xNDQuemVuby5fbSIsInJ0dGwiOjUsImp0aSI6Im5nQmJkeTBjU3QtSlhMeG5QczVMUUEiLCJpYXQiOjE3NDM5MTMxNTksImV4cCI6MTc0MzkxMzIxOX0.bBtX4N1gdSrYDAPnoVAvA_OR42oPE3ceaGueOZW5dkg", logo: "https://raw.githubusercontent.com/Omoluabi1003/Ariyo-AI/main/logo.jpg" },
  { name: "Faaji 106.5 FM", location: "Lagos", url: "http://streaming.faajifmradio.com:8000/faaji", logo: "https://raw.githubusercontent.com/Omoluabi1003/Ariyo-AI/main/logo.jpg" },
  { name: "EgbaAlake Radio", location: "Attleboro Falls, USA", url: "https://centova47.instainternet.com/proxy/egbaalak?mp=/stream", logo: "https://raw.githubusercontent.com/Omoluabi1003/Ariyo-AI/main/logo.jpg" },
  { name: "Ray Power FM", location: "Abuja", url: "https://streamlive2.hearthis.at:8080/9065169.ogg", logo: "https://raw.githubusercontent.com/Omoluabi1003/Ariyo-AI/main/logo.jpg" },
  { name: "Jay 101.9 FM", location: "Jos", url: "https://stream2.rcast.net/69640/", logo: "https://raw.githubusercontent.com/Omoluabi1003/Ariyo-AI/main/logo.jpg" },
  { name: "Apostolic Flame Radio", location: "Ibadan", url: "https://hoth.alonhosting.com:1695/stream", logo: "https://raw.githubusercontent.com/Omoluabi1003/Ariyo-AI/main/logo.jpg" },
  { name: "FRCN Lagos Metro FM", location: "Abuja", url: "http://go.webgateready.com:7668/;", logo: "https://raw.githubusercontent.com/Omoluabi1003/Ariyo-AI/main/logo.jpg" },
  { name: "Radio Nigeria", location: "Abuja", url: "https://stream.radionigeria.gov.ng/live", logo: "https://raw.githubusercontent.com/Omoluabi1003/Ariyo-AI/main/logo.jpg" },
  { name: "NBS Solid 97.1 FM", location: "Nassarawa", url: "https://nbsradio1.radioca.st/;", logo: "https://raw.githubusercontent.com/Omoluabi1003/Ariyo-AI/main/logo.jpg" },
  { name: "Vision Africa Radio", location: "Abia", url: "https://xstreamer.galcom.org:8443/VisionAfrica", logo: "https://raw.githubusercontent.com/Omoluabi1003/Ariyo-AI/main/logo.jpg" },
  { name: "ITMP Radio", location: "Florida", url: "http://uk4freenew.listen2myradio.com:32739/stream", logo: "https://raw.githubusercontent.com/Omoluabi1003/Ariyo-AI/main/logo.jpg" },
  { name: "Crest 106.1 FM", location: "Ondo", url: "https://stream-154.zeno.fm/9cgtkwg3teruv?zt=eyJhbGciOiJIUzI1NiJ9.eyJzdHJlYW0iOiI5Y2d0a3dnM3RlcnV2IiwiaG9zdCI6InN0cmVhbS0xNTQuemVuby5fbSIsInJ0dGwiOjUsImp0aSI6IlI4MXQzdjhRUWhDQWdkODRsaWJtckEiLCJpYXQiOjE3NDM5MTI3NzQsImV4cCI6MTc0MzkxMjgzNH0.QiIm090_iZfI55MZu7WqKjm5inX-mmKanKQgGBBbA7w", logo: "https://raw.githubusercontent.com/Omoluabi1003/Ariyo-AI/main/logo.jpg" },
  { name: "Eko FM", location: "Lagos", url: "https://servoserver.com.ng/ekofmradiolagos/stream/1/live.mp3", logo: "https://raw.githubusercontent.com/Omoluabi1003/Ariyo-AI/main/logo.jpg" },
  { name: "Liveway Radio Network FM", location: "Lagos", url: "https://stream-173.zeno.fm/qc43ktn6n0quv?zt=eyJhbGciOiJIUzI1NiJ9.eyJzdHJlYW0iOiJxYzQza3RuNm4wcXV2IiwiaG9zdCI6InN0cmVhbS0xNzMuemVuby5fbSIsInJ0dGwiOjUsImp0aSI6ImMtb0ZiQ3dtTE1hZUlEVU5YQ3BiVUEiLCJpYXQiOjE3NDM5MTMyODcsImV4cCI6MTc0MzkxMzM0N30.HVLieksgqvV_vsqRr9_rcDexkz6Lqeqeu7stKvuJr10", logo: "https://raw.githubusercontent.com/Omoluabi1003/Ariyo-AI/main/logo.jpg" },
  { name: "Radio Space FM", location: "Ibadan", url: "https://stream-175.zeno.fm/79hmhafteg0uv?zt=eyJhbGciOiJIUzI1NiJ9.eyJzdHJlYW0iOiI3OWhtaGFmdGVnMHV2IiwiaG9zdCI6InN0cmVhbS0xNzUuemVuby5fbSIsInJ0dGwiOjUsImp0aSI6IkFqako3a0doUllPcVB1cmY3RDJmN2ciLCJpYXQiOjE3NDM5MTM0NzUsImV4cCI6MTc0MzkxMzUzNX0.Ow_YytmLcyURU6d_ji4EvQ-4YuLvJjXATerfWMHO67o", logo: "https://raw.githubusercontent.com/Omoluabi1003/Ariyo-AI/main/logo.jpg" },
  { name: "Comfort 95.1 FM", location: "Uyo", url: "https://a3.asurahosting.com:7770/radio.mp3", logo: "https://raw.githubusercontent.com/Omoluabi1003/Ariyo-AI/main/logo.jpg" },
  { name: "AKBC Akwa Ibom Radio", location: "Uyo", url: "https://stream-175.zeno.fm/2ttc8yl6giztv?zt=eyJhbGciOiJIUzI1NiJ9.eyJzdHJlYW0iOiIydHRjOHlsNmdpenR2IiwiaG9zdCI6InN0cmVhbS0xNzUuemVuby5fbSIsInJ0dGwiOjUsImp0aSI6IlE5VFpTRXpOUzFTMVlHSHdxaW5sQWciLCJpYXQiOjE3NDM5MTM3NjgsImV4cCI6MTc0MzkxMzgyOH0.9X5nRAtcN_4Pv-z5uE6ukYrNEIcwW0gHTVuYUlxVCj4", logo: "https://raw.githubusercontent.com/Omoluabi1003/Ariyo-AI/main/logo.jpg" },
  { name: "Amen Radio", location: "Lagos", url: "https://eu3.fastcast4u.com/proxy/amenradi?mp=/stream", logo: "https://raw.githubusercontent.com/Omoluabi1003/Ariyo-AI/main/logo.jpg" },
  { name: "Apala Radio", location: "Ibadan", url: "https://stream-172.zeno.fm/fqcszwwxra0uv?zt=eyJhbGciOiJIUzI1NiJ9.eyJzdHJlYW0iOiJmcWNzend3eHJhMHV2IiwiaG9zdCI6InN0cmVhbS0xNzIuemVuby5mbSIsInJ0dGwiOjUsImp0aSI6IjMtaGJNc2Z6UU82U1VKWlNHbExkcFEiLCJpYXQiOjE3NDQyMjUzMDYsImV4cCI6MTc0NDIyNTM2Nn0.wncuUShs9-mnbAj3ndGGS9qd1z6AHtBzJEgT9b7NZDY", logo: "https://raw.githubusercontent.com/Omoluabi1003/Ariyo-AI/main/logo.jpg" },
  { name: "WFM 91.77 Women Radio", location: "Lagos", url: "https://s28.myradiostream.com:11618/listen.mp3", logo: "https://raw.githubusercontent.com/Omoluabi1003/Ariyo-AI/main/logo.jpg" },
  { name: "RFI Haoussa", location: "Nigeria", url: "https://rfihaoussa96k.ice.infomaniak.ch/rfihaoussa-96k.mp3", logo: "https://raw.githubusercontent.com/Omoluabi1003/Ariyo-AI/main/logo.jpg" },
  { name: "Tungba FM", location: "Lagos", url: "https://stream-173.zeno.fm/3vd633m7ctzuv?zt=eyJhbGciOiJIUzI1NiJ9.eyJzdHJlYW0iOiIzdmQ2MzNtN2N0enV2IiwiaG9zdCI6InN0cmVhbS0xNzMuemVuby5fbSIsInJ0dGwiOjUsImp0aSI6Im9QY19lN292UWFLdGUxSjFuNTI3M2ciLCJpYXQiOjE3NDM5MTQ0OTEsImV4cCI6MTc0MzkxNDU1MX0.UvA6Q0NuULFeRcHvqPJ9d68DeWz-0agoUBi8GDQWN0E", logo: "https://raw.githubusercontent.com/Omoluabi1003/Ariyo-AI/main/logo.jpg" },
  { name: "Siren Songs", location: "Belgium", url: "https://sirensongs-mynoise.radioca.st/live", logo: "https://raw.githubusercontent.com/Omoluabi1003/Ariyo-AI/main/logo.jpg" },
  { name: "Radio Relax", location: "Ukraine", url: "https://online.radiorelax.ua/RadioRelax_Instrumental_HD", logo: "https://raw.githubusercontent.com/Omoluabi1003/Ariyo-AI/main/logo.jpg" },
  { name: "Exclusively Kenny G", location: "Dubai", url: "https://2.mystreaming.net/er/kennyg/icecast.audio", logo: "https://raw.githubusercontent.com/Omoluabi1003/Ariyo-AI/main/logo.jpg" },
  { name: "Exclusively Jim Reeves", location: "Dubai", url: "https://nl4.mystreaming.net/er/jimreeves/icecast.audio", logo: "https://raw.githubusercontent.com/Omoluabi1003/Ariyo-AI/main/logo.jpg" },
  { name: "247 Praise Radio", location: "Jacksonville, Florida", url: "https://streaming.radio.co/s6da23ac69/listen", logo: "https://raw.githubusercontent.com/Omoluabi1003/Ariyo-AI/main/logo.jpg" },
  { name: "NPR News", location: "Washington DC", url: "https://npr-ice.streamguys1.com/live.mp3", logo: "https://raw.githubusercontent.com/Omoluabi1003/Ariyo-AI/main/logo.jpg" },
  { name: "Al Jazeera", location: "Qatar", url: "https://live-hls-audio-web-aje.getaj.net/VOICE-AJE/01.m3u8", logo: "https://raw.githubusercontent.com/Omoluabi1003/Ariyo-AI/main/logo.jpg" },
  { name: "CNN International", location: "Atlanta", url: "https://tunein.cdnstream1.com/3519_96.aac", logo: "https://raw.githubusercontent.com/Omoluabi1003/Ariyo-AI/main/logo.jpg" },
  { name: "BBC World Service", location: "London", url: "https://utulsa.streamguys1.com/KWGSHD3-MP3", logo: "https://raw.githubusercontent.com/Omoluabi1003/Ariyo-AI/main/logo.jpg" },
  { name: "BBC World Service", location: "West Africa", url: "https://stream.live.vc.bbcmedia.co.uk/bbc_world_service_west_africa", logo: "https://raw.githubusercontent.com/Omoluabi1003/Ariyo-AI/main/logo.jpg" },
  { name: "BBC World Service", location: "South Asia", url: "https://stream.live.vc.bbcmedia.co.uk/bbc_world_service_south_asia", logo: "https://raw.githubusercontent.com/Omoluabi1003/Ariyo-AI/main/logo.jpg" },
  { name: "BBC World Service", location: "Vermont", url: "https://vprbbc.streamguys1.com/vprbbc24.mp3", logo: "https://raw.githubusercontent.com/Omoluabi1003/Ariyo-AI/main/logo.jpg" },
  { name: "Capital FM", location: "London", url: "https://media-ssl.musicradio.com/CapitalMP3", logo: "https://raw.githubusercontent.com/Omoluabi1003/Ariyo-AI/main/logo.jpg" },
  { name: "WNYC", location: "New York", url: "https://fm939.wnyc.org/wnycfm-tunein", logo: "https://raw.githubusercontent.com/Omoluabi1003/Ariyo-AI/main/logo.jpg" },
  { name: "RTE Radio 1", location: "Dublin", url: "https://icecast.rte.ie/radio1", logo: "https://raw.githubusercontent.com/Omoluabi1003/Ariyo-AI/main/logo.jpg" },
  { name: "Virgin Radio UK", location: "London", url: "https://radio.virginradio.co.uk/stream", logo: "https://raw.githubusercontent.com/Omoluabi1003/Ariyo-AI/main/logo.jpg" },
  { name: "WBEZ", location: "Chicago", url: "http://wbez.streamguys1.com/wbez128.mp3", logo: "https://raw.githubusercontent.com/Omoluabi1003/Ariyo-AI/main/logo.jpg" },
  { name: "Talk Sport", location: "London", url: "https://radio.talksport.com/stream", logo: "https://raw.githubusercontent.com/Omoluabi1003/Ariyo-AI/main/logo.jpg" },
  { name: "Talk Sport 2", location: "London", url: "https://radio.talksport.com/stream2", logo: "https://raw.githubusercontent.com/Omoluabi1003/Ariyo-AI/main/logo.jpg" },
  { name: "Joy FM", location: "Accra", url: "http://provisioning.streamtheworld.com/pls/JOY_FM.pls", logo: "https://raw.githubusercontent.com/Omoluabi1003/Ariyo-AI/main/logo.jpg" },
  { name: "UBC Radio", location: "Kampala", url: "https://stream.ubc.go.ug/ubcradio", logo: "https://raw.githubusercontent.com/Omoluabi1003/Ariyo-AI/main/logo.jpg" },
  { name: "Metro FM", location: "Johannesburg", url: "https://playerservices.streamtheworld.com/api/livestream-redirect/METRO_FM.mp3", logo: "https://raw.githubusercontent.com/Omoluabi1003/Ariyo-AI/main/logo.jpg" },
  { name: "Black Information Network", location: "USA", url: "https://cloud.revma.ihrhls.com/zc8729?rj-org=n2db-e2&rj-ttl=5&rj-tok=AAABlmL2wq8ALLTq8zLJ1wWRdw", logo: "https://raw.githubusercontent.com/Omoluabi1003/Ariyo-AI/main/logo.jpg" },
  { name: "947", location: "Johannesburg", url: "https://playerservices.streamtheworld.com/api/livestream-redirect/FM947.mp3", logo: "https://raw.githubusercontent.com/Omoluabi1003/Ariyo-AI/main/logo.jpg" }
];
